
(provide 'colors)

(eval-when-compile    (require 'color-theme))
(defun my-color-theme ()
  "Color theme by Yury Luneff, created 2008-03-30."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "AntiqueWhite3")
      (background-mode . light)
      (background-toolbar-color . "#cccccccccccc")
      (border-color . "#000000000000")
      (bottom-toolbar-shadow-color . "#7a7a7a7a7a7a")
      (cursor-color . "Red3")
      (foreground-color . "black")
      (mouse-color . "black")
      (senator-eldoc-use-color . t)
      (top-toolbar-shadow-color . "#f5f5f5f5f5f5")
      (vc-annotate-very-old-color . "#0046FF")
      (viper-saved-cursor-color-in-replace-mode . "Red3"))
     ((compilation-message-face . underline)
      (display-time-mail-face . mode-line)
      (ecb-analyse-bucket-element-face . ecb-analyse-bucket-element-face)
      (ecb-analyse-bucket-node-face . ecb-analyse-bucket-node-face)
      (ecb-analyse-face . ecb-default-highlight-face)
      (ecb-analyse-general-face . ecb-default-general-face)
      (ecb-directories-general-face . ecb-directories-general-face)
      (ecb-directory-face . ecb-directory-face)
      (ecb-directory-not-accessible-face . ecb-directory-not-accessible-face)
      (ecb-history-face . ecb-history-face)
      (ecb-history-general-face . ecb-history-general-face)
      (ecb-method-face . ecb-method-face)
      (ecb-method-non-semantic-face . speedbar-tag-face)
      (ecb-methods-general-face . ecb-methods-general-face)
      (ecb-mode-line-data-face . ecb-mode-line-data-face)
      (ecb-mode-line-prefix-face . ecb-mode-line-prefix-face)
      (ecb-mode-line-win-nr-face . ecb-mode-line-win-nr-face)
      (ecb-source-face . ecb-source-face)
      (ecb-source-in-directories-buffer-face . ecb-sources-face)
      (ecb-source-read-only-face . ecb-source-read-only-face)
      (ecb-sources-general-face . ecb-sources-general-face)
      (ecb-tag-header-face . ecb-tag-header-face)
      (ecb-tree-guide-line-face . ecb-tree-guide-line-face)
      (goto-address-mail-face . italic)
      (goto-address-mail-mouse-face . secondary-selection)
      (goto-address-url-face . bold)
      (goto-address-url-mouse-face . highlight)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . bold)
      (rmail-highlight-face . font-lock-function-name-face)
      (vc-annotate-very-old-color . "#0046FF")
      (view-highlight-face . highlight)
      (whitespace-display-spaces-in-color . t)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "AntiqueWhite3" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 151 :width normal :family "xos4-terminus"))))
     (Buffer-menu-buffer-face ((t (nil))))
     (CUA-global-mark-face ((t (:background "cyan" :foreground "black"))))
     (CUA-rectangle-face ((t (:background "maroon" :foreground "white"))))
     (CUA-rectangle-noselect-face ((t (:background "dimgray" :foreground "white"))))
     (Info-title-1-face ((t (nil))))
     (Info-title-2-face ((t (nil))))
     (Info-title-3-face ((t (nil))))
     (Info-title-4-face ((t (nil))))
     (antlr-font-lock-keyword-face ((t (nil))))
     (antlr-font-lock-literal-face ((t (nil))))
     (antlr-font-lock-ruledef-face ((t (nil))))
     (antlr-font-lock-ruleref-face ((t (nil))))
     (antlr-font-lock-tokendef-face ((t (nil))))
     (antlr-font-lock-tokenref-face ((t (nil))))
     (bbdb-company ((t (:italic t :slant italic))))
     (bbdb-field-name ((t (:bold t :weight bold))))
     (bbdb-field-value ((t (nil))))
     (bbdb-name ((t (:underline t))))
     (bg:erc-color-face0 ((t (nil))))
     (bg:erc-color-face1 ((t (nil))))
     (bg:erc-color-face10 ((t (nil))))
     (bg:erc-color-face11 ((t (nil))))
     (bg:erc-color-face12 ((t (nil))))
     (bg:erc-color-face13 ((t (nil))))
     (bg:erc-color-face14 ((t (nil))))
     (bg:erc-color-face15 ((t (nil))))
     (bg:erc-color-face2 ((t (nil))))
     (bg:erc-color-face3 ((t (nil))))
     (bg:erc-color-face4 ((t (nil))))
     (bg:erc-color-face5 ((t (nil))))
     (bg:erc-color-face6 ((t (nil))))
     (bg:erc-color-face7 ((t (nil))))
     (bg:erc-color-face8 ((t (nil))))
     (bg:erc-color-face9 ((t (nil))))
     (blank-space-face ((t (nil))))
     (blank-tab-face ((t (nil))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (:background "#000000000000"))))
     (border-glyph ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (buffers-tab ((t (nil))))
     (button ((t (nil))))
     (c-nonbreakable-space-face ((t (:bold t :background "Pink" :weight bold))))
     (calendar-today ((t (:background "Spring Green" :foreground "Brown" :underline t))))
     (change-log-acknowledgement-face ((t (nil))))
     (change-log-conditionals-face ((t (nil))))
     (change-log-date-face ((t (nil))))
     (change-log-email-face ((t (nil))))
     (change-log-file-face ((t (nil))))
     (change-log-function-face ((t (nil))))
     (change-log-list-face ((t (nil))))
     (change-log-name-face ((t (nil))))
     (clear-case-mode-string-face ((t (:bold t :background "grey" :foreground "black" :box (:line-width 2 :color "grey" :style released-button) :weight bold :height 0.9 :family "Arial"))))
     (clearcase-dired-checkedout-face ((t (nil))))
     (comint-highlight-input ((t (nil))))
     (comint-highlight-prompt ((t (nil))))
     (comint-input-face ((t (:foreground "deepskyblue"))))
     (compilation-column-number ((t (:foreground "darkgreen"))))
     (compilation-error ((t (:bold t :weight bold :foreground "Red"))))
     (compilation-info ((t (:bold t :foreground "Green3" :weight bold))))
     (compilation-line-number ((t (:foreground "black"))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-common-part ((t (:family "xos4-terminus" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "AntiqueWhite3" :stipple nil :height 151))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cparen-around-andor-face ((t (nil))))
     (cparen-around-begin-face ((t (nil))))
     (cparen-around-conditional-face ((t (nil))))
     (cparen-around-define-face ((t (nil))))
     (cparen-around-lambda-face ((t (nil))))
     (cparen-around-letdo-face ((t (nil))))
     (cparen-around-quote-face ((t (nil))))
     (cparen-around-set!-face ((t (nil))))
     (cparen-around-syntax-rules-face ((t (nil))))
     (cparen-around-vector-face ((t (nil))))
     (cparen-binding-face ((t (nil))))
     (cparen-binding-list-face ((t (nil))))
     (cparen-conditional-clause-face ((t (nil))))
     (cparen-normal-paren-face ((t (nil))))
     (cperl-array-face ((t (nil))))
     (cperl-hash-face ((t (nil))))
     (cperl-invalid-face ((t (nil))))
     (cperl-nonoverridable-face ((t (nil))))
     (cscope-file-face ((t (:foreground "blue"))))
     (cscope-function-face ((t (:foreground "magenta"))))
     (cscope-line-face ((t (:foreground "green"))))
     (cscope-line-number-face ((t (:foreground "red"))))
     (cscope-mouse-face ((t (:background "blue" :foreground "white"))))
     (cursor ((t (:background "Red3" :foreground "black"))))
     (custom-button ((t (:background "dark slate grey" :foreground "azure"))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (nil))))
     (custom-button-pressed-unraised ((t (:underline t :foreground "magenta4"))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (nil))))
     (custom-comment ((t (nil))))
     (custom-comment-tag ((t (nil))))
     (custom-documentation ((t (:background "white" :foreground "blue"))))
     (custom-face-tag ((t (nil))))
     (custom-group-tag ((t (nil))))
     (custom-group-tag-1 ((t (nil))))
     (custom-invalid ((t (nil))))
     (custom-link ((t (:underline t :foreground "blue1"))))
     (custom-modified ((t (nil))))
     (custom-rogue ((t (nil))))
     (custom-saved ((t (nil))))
     (custom-set ((t (nil))))
     (custom-state ((t (nil))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (nil))))
     (custom-variable-tag ((t (nil))))
     (cvs-filename-face ((t (nil))))
     (cvs-handled-face ((t (nil))))
     (cvs-header-face ((t (nil))))
     (cvs-marked-face ((t (nil))))
     (cvs-msg-face ((t (nil))))
     (cvs-need-action-face ((t (nil))))
     (cvs-unknown-face ((t (nil))))
     (cyan ((t (nil))))
     (date ((t (:foreground "green"))))
     (diary ((t (:background "navy" :foreground "yellow"))))
     (diff-added-face ((t (nil))))
     (diff-changed-face ((t (nil))))
     (diff-context-face ((t (nil))))
     (diff-file-header-face ((t (nil))))
     (diff-function-face ((t (nil))))
     (diff-header-face ((t (nil))))
     (diff-hunk-header-face ((t (nil))))
     (diff-index-face ((t (nil))))
     (diff-nonexistent-face ((t (nil))))
     (diff-removed-face ((t (nil))))
     (dired-face-boring ((t (:foreground "Gray65"))))
     (dired-face-directory ((t (:bold t :weight bold))))
     (dired-face-executable ((t (:foreground "SeaGreen"))))
     (dired-face-flagged ((t (:background "LightSlateGray"))))
     (dired-face-header ((t (nil))))
     (dired-face-marked ((t (:background "PaleVioletRed"))))
     (dired-face-permissions ((t (:background "grey75" :foreground "black"))))
     (dired-face-setuid ((t (:foreground "Red"))))
     (dired-face-socket ((t (:foreground "magenta"))))
     (dired-face-symlink ((t (:foreground "cyan"))))
     (display-time-mail-balloon-enhance-face ((t (:background "orange"))))
     (display-time-mail-balloon-gnus-group-face ((t (:foreground "blue"))))
     (display-time-time-balloon-face ((t (:foreground "red"))))
     (ebrowse-default-face ((t (nil))))
     (ebrowse-file-name-face ((t (nil))))
     (ebrowse-member-attribute-face ((t (nil))))
     (ebrowse-member-class-face ((t (nil))))
     (ebrowse-progress-face ((t (nil))))
     (ebrowse-root-class-face ((t (nil))))
     (ebrowse-tree-mark-face ((t (nil))))
     (ecb-analyse-bucket-element-face ((t (:foreground "brown" :height 1.0))))
     (ecb-analyse-bucket-node-face ((t (:bold t :weight bold :height 1.0))))
     (ecb-analyse-face ((t (:background "cornflower blue" :foreground "yellow" :height 1.0))))
     (ecb-analyse-general-face ((t (:height 1.0))))
     (ecb-bucket-node-face ((t (:bold t :weight bold :height 1.0))))
     (ecb-bucket-token-face ((t (:bold t :weight bold))))
     (ecb-default-general-face ((t (:height 1.0))))
     (ecb-default-highlight-face ((t (:background "magenta" :height 1.0))))
     (ecb-directories-general-face ((t (:height 0.9))))
     (ecb-directory-face ((t (:background "Cyan4"))))
     (ecb-directory-not-accessible-face ((t (:foreground "gray60" :height 1.0))))
     (ecb-history-face ((t (:background "Cyan4"))))
     (ecb-history-general-face ((t (:height 0.9))))
     (ecb-method-face ((t (:background "Cyan4" :slant normal :weight normal))))
     (ecb-method-non-semantic-face ((t (:slant normal :foreground "brown"))))
     (ecb-methods-general-face ((t (:slant normal))))
     (ecb-mode-line-data-face ((t (nil))))
     (ecb-mode-line-prefix-face ((t (:foreground "forestgreen"))))
     (ecb-mode-line-win-nr-face ((t (:bold t :weight bold))))
     (ecb-source-face ((t (:background "Cyan4"))))
     (ecb-source-in-directories-buffer-face ((t (:foreground "LightBlue1"))))
     (ecb-source-read-only-face ((t (:italic t :slant italic))))
     (ecb-sources-face ((t (nil))))
     (ecb-sources-general-face ((t (:height 0.9))))
     (ecb-tag-header-face ((t (:background "SeaGreen1"))))
     (ecb-token-header-face ((t (:background "Steelblue4"))))
     (ecb-tree-guide-line-face ((t (:foreground "grey" :height 1.0))))
     (ecb-type-tag-class-face ((t (:bold t :weight bold))))
     (ecb-type-tag-enum-face ((t (:bold t :weight bold))))
     (ecb-type-tag-group-face ((t (:bold t :foreground "dim gray" :weight bold))))
     (ecb-type-tag-interface-face ((t (:bold t :weight bold))))
     (ecb-type-tag-struct-face ((t (:bold t :weight bold))))
     (ecb-type-tag-typedef-face ((t (:bold t :weight bold))))
     (ecb-type-tag-union-face ((t (:bold t :weight bold))))
     (ecb-type-token-class-face ((t (:bold t :weight bold))))
     (ecb-type-token-enum-face ((t (:bold t :weight bold))))
     (ecb-type-token-group-face ((t (:bold t :foreground "dim gray" :weight bold))))
     (ecb-type-token-interface-face ((t (:bold t :weight bold))))
     (ecb-type-token-struct-face ((t (:bold t :weight bold))))
     (ecb-type-token-typedef-face ((t (:bold t :weight bold))))
     (edb-inter-field-face ((t (nil))))
     (edb-normal-summary-face ((t (nil))))
     (ediff-current-diff-face-A ((t (nil))))
     (ediff-current-diff-face-Ancestor ((t (nil))))
     (ediff-current-diff-face-B ((t (nil))))
     (ediff-current-diff-face-C ((t (nil))))
     (ediff-even-diff-face-A ((t (nil))))
     (ediff-even-diff-face-Ancestor ((t (nil))))
     (ediff-even-diff-face-B ((t (nil))))
     (ediff-even-diff-face-C ((t (nil))))
     (ediff-fine-diff-face-A ((t (nil))))
     (ediff-fine-diff-face-Ancestor ((t (nil))))
     (ediff-fine-diff-face-B ((t (nil))))
     (ediff-fine-diff-face-C ((t (nil))))
     (ediff-odd-diff-face-A ((t (nil))))
     (ediff-odd-diff-face-Ancestor ((t (nil))))
     (ediff-odd-diff-face-B ((t (nil))))
     (ediff-odd-diff-face-C ((t (nil))))
     (eieio-custom-slot-tag-face ((t (nil))))
     (emacs-wiki-bad-link-face ((t (nil))))
     (emacs-wiki-link-face ((t (nil))))
     (erc-action-face ((t (nil))))
     (erc-bold-face ((t (nil))))
     (erc-current-nick-face ((t (nil))))
     (erc-dangerous-host-face ((t (nil))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (nil))))
     (erc-error-face ((t (nil))))
     (erc-fool-face ((t (nil))))
     (erc-highlight-face ((t (nil))))
     (erc-host-danger-face ((t (:foreground "red"))))
     (erc-input-face ((t (nil))))
     (erc-inverse-face ((t (nil))))
     (erc-keyword-face ((t (nil))))
     (erc-nick-default-face ((t (nil))))
     (erc-nick-msg-face ((t (nil))))
     (erc-notice-face ((t (nil))))
     (erc-pal-face ((t (nil))))
     (erc-prompt-face ((t (nil))))
     (erc-timestamp-face ((t (nil))))
     (erc-underline-face ((t (nil))))
     (escape-glyph ((t (:foreground "brown"))))
     (eshell-ls-archive-face ((t (nil))))
     (eshell-ls-backup-face ((t (nil))))
     (eshell-ls-clutter-face ((t (nil))))
     (eshell-ls-directory-face ((t (nil))))
     (eshell-ls-executable-face ((t (nil))))
     (eshell-ls-missing-face ((t (nil))))
     (eshell-ls-picture-face ((t (nil))))
     (eshell-ls-product-face ((t (nil))))
     (eshell-ls-readonly-face ((t (nil))))
     (eshell-ls-special-face ((t (nil))))
     (eshell-ls-symlink-face ((t (nil))))
     (eshell-ls-text-face ((t (nil))))
     (eshell-ls-todo-face ((t (nil))))
     (eshell-ls-unreadable-face ((t (nil))))
     (eshell-prompt-face ((t (nil))))
     (eshell-test-failed-face ((t (nil))))
     (eshell-test-ok-face ((t (nil))))
     (excerpt ((t (nil))))
     (extra-whitespace-face ((t (nil))))
     (face-1 ((t (:stipple nil :foreground "royal blue" :family "andale mono"))))
     (face-2 ((t (:stipple nil :foreground "DeepSkyBlue1" :overline nil :underline nil :slant normal :family "outline-andale mono"))))
     (face-3 ((t (:stipple nil :foreground "NavajoWhite3"))))
     (ff-paths-non-existant-file-face ((t (:bold t :foreground "NavyBlue" :weight bold))))
     (fg:black ((t (nil))))
     (fg:erc-color-face0 ((t (nil))))
     (fg:erc-color-face1 ((t (nil))))
     (fg:erc-color-face10 ((t (nil))))
     (fg:erc-color-face11 ((t (nil))))
     (fg:erc-color-face12 ((t (nil))))
     (fg:erc-color-face13 ((t (nil))))
     (fg:erc-color-face14 ((t (nil))))
     (fg:erc-color-face15 ((t (nil))))
     (fg:erc-color-face2 ((t (nil))))
     (fg:erc-color-face3 ((t (nil))))
     (fg:erc-color-face4 ((t (nil))))
     (fg:erc-color-face5 ((t (nil))))
     (fg:erc-color-face6 ((t (nil))))
     (fg:erc-color-face7 ((t (nil))))
     (fg:erc-color-face8 ((t (nil))))
     (fg:erc-color-face9 ((t (nil))))
     (file-name-shadow ((t (:foreground "grey50"))))
     (fixed ((t (nil))))
     (fixed-pitch ((t (nil))))
     (fl-comment-face ((t (nil))))
     (fl-function-name-face ((t (nil))))
     (fl-keyword-face ((t (nil))))
     (fl-string-face ((t (nil))))
     (fl-type-face ((t (nil))))
     (flash-paren-face-off ((t (nil))))
     (flash-paren-face-on ((t (nil))))
     (flash-paren-face-region ((t (nil))))
     (flyspell-duplicate-face ((t (nil))))
     (flyspell-incorrect-face ((t (nil))))
     (font-latex-bold-face ((t (:bold t :foreground "DarkOliveGreen" :weight bold))))
     (font-latex-italic-face ((t (:italic t :foreground "DarkOliveGreen" :slant italic))))
     (font-latex-math-face ((t (:foreground "navy"))))
     (font-latex-sedate-face ((t (:foreground "DimGray"))))
     (font-latex-string-face ((t (nil))))
     (font-latex-warning-face ((t (nil))))
     (font-lock-builtin-face ((t (:foreground "red3"))))
     (font-lock-comment-delimiter-face ((t (:foreground "blue"))))
     (font-lock-comment-face ((t (:foreground "blue"))))
     (font-lock-constant-face ((t (:foreground "red3"))))
     (font-lock-doc-face ((t (nil))))
     (font-lock-doc-string-face ((t (:foreground "mediumvioletred"))))
     (font-lock-exit-face ((t (nil))))
     (font-lock-function-name-face ((t (:foreground "firebrick"))))
     (font-lock-keyword-face ((t (:bold t :foreground "black" :weight bold))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-other-emphasized-face ((t (nil))))
     (font-lock-other-type-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "blue3"))))
     (font-lock-reference-face ((t (:foreground "red3"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-special-comment-face ((t (:foreground "blue4"))))
     (font-lock-special-keyword-face ((t (:foreground "red4"))))
     (font-lock-string-face ((t (:foreground "mediumvioletred"))))
     (font-lock-type-face ((t (:foreground "darkgreen"))))
     (font-lock-variable-name-face ((t (:foreground "black"))))
     (font-lock-warning-face ((t (:bold t :foreground "Red" :weight bold))))
     (fringe ((t (nil))))
     (gdb-arrow-face ((t (:bold t :background "yellow" :foreground "red" :weight bold))))
     (gnus-cite-attribution-face ((t (:italic t :slant italic))))
     (gnus-cite-face-1 ((t (:foreground "MidnightBlue"))))
     (gnus-cite-face-10 ((t (:foreground "medium purple"))))
     (gnus-cite-face-11 ((t (:foreground "turquoise"))))
     (gnus-cite-face-2 ((t (:foreground "firebrick"))))
     (gnus-cite-face-3 ((t (:foreground "dark green"))))
     (gnus-cite-face-4 ((t (:foreground "OrangeRed"))))
     (gnus-cite-face-5 ((t (:foreground "dark khaki"))))
     (gnus-cite-face-6 ((t (:foreground "dark violet"))))
     (gnus-cite-face-7 ((t (:foreground "SteelBlue4"))))
     (gnus-cite-face-8 ((t (:foreground "magenta"))))
     (gnus-cite-face-9 ((t (:foreground "violet"))))
     (gnus-emphasis-bold ((t (:bold t :weight bold))))
     (gnus-emphasis-bold-italic ((t (:bold t :weight bold))))
     (gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
     (gnus-emphasis-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-strikethru ((t (nil))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :underline t :weight bold))))
     (gnus-emphasis-underline-bold-italic ((t (:bold t :underline t :weight bold))))
     (gnus-emphasis-underline-italic ((t (:italic t :underline t :slant italic))))
     (gnus-filterhist-face-1 ((t (nil))))
     (gnus-group-mail-1-empty-face ((t (:foreground "DeepPink3"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "DeepPink3" :weight bold))))
     (gnus-group-mail-2-empty-face ((t (:foreground "HotPink3"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "HotPink3" :weight bold))))
     (gnus-group-mail-3-empty-face ((t (:foreground "magenta4"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "magenta4" :weight bold))))
     (gnus-group-mail-low-empty-face ((t (:foreground "DeepPink4"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "DeepPink4" :weight bold))))
     (gnus-group-news-1-empty-face ((t (:foreground "ForestGreen"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (gnus-group-news-2-empty-face ((t (:foreground "CadetBlue4"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "CadetBlue4" :weight bold))))
     (gnus-group-news-3-empty-face ((t (nil))))
     (gnus-group-news-3-face ((t (:bold t :weight bold))))
     (gnus-group-news-4-empty-face ((t (nil))))
     (gnus-group-news-4-face ((t (:bold t :weight bold))))
     (gnus-group-news-5-empty-face ((t (nil))))
     (gnus-group-news-5-face ((t (:bold t :weight bold))))
     (gnus-group-news-6-empty-face ((t (nil))))
     (gnus-group-news-6-face ((t (:bold t :weight bold))))
     (gnus-group-news-low-empty-face ((t (:foreground "DarkGreen"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "DarkGreen" :weight bold))))
     (gnus-header-content-face ((t (:italic t :foreground "indianred4" :slant italic))))
     (gnus-header-from-face ((t (:foreground "red3"))))
     (gnus-header-name-face ((t (:foreground "maroon"))))
     (gnus-header-newsgroups-face ((t (:italic t :foreground "MidnightBlue" :slant italic))))
     (gnus-header-subject-face ((t (:foreground "red4"))))
     (gnus-picon-face ((t (nil))))
     (gnus-picon-xbm-face ((t (nil))))
     (gnus-picons-face ((t (:background "white" :foreground "black"))))
     (gnus-picons-xbm-face ((t (:background "white" :foreground "black"))))
     (gnus-server-agent-face ((t (nil))))
     (gnus-server-closed-face ((t (nil))))
     (gnus-server-denied-face ((t (nil))))
     (gnus-server-offline-face ((t (nil))))
     (gnus-server-opened-face ((t (nil))))
     (gnus-signature-face ((t (:italic t :slant italic))))
     (gnus-splash ((t (nil))))
     (gnus-splash-face ((t (:foreground "Brown"))))
     (gnus-summary-cancelled-face ((t (:background "black" :foreground "yellow"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "RoyalBlue" :weight bold))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "DarkGreen" :weight bold))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "firebrick" :weight bold))))
     (gnus-summary-high-undownloaded-face ((t (nil))))
     (gnus-summary-high-unread-face ((t (:bold t :weight bold))))
     (gnus-summary-low-ancient-face ((t (:italic t :foreground "RoyalBlue" :slant italic))))
     (gnus-summary-low-read-face ((t (:italic t :foreground "DarkGreen" :slant italic))))
     (gnus-summary-low-ticked-face ((t (:italic t :foreground "firebrick" :slant italic))))
     (gnus-summary-low-undownloaded-face ((t (nil))))
     (gnus-summary-low-unread-face ((t (:italic t :slant italic))))
     (gnus-summary-normal-ancient-face ((t (:foreground "RoyalBlue"))))
     (gnus-summary-normal-read-face ((t (:foreground "DarkGreen"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "firebrick"))))
     (gnus-summary-normal-undownloaded-face ((t (nil))))
     (gnus-summary-normal-unread-face ((t (nil))))
     (gnus-summary-selected-face ((t (:underline t))))
     (gnus-x-face ((t (:background "white" :foreground "black"))))
     (green ((t (:foreground "green"))))
     (gui-button-face ((t (:background "grey75" :foreground "black"))))
     (gui-element ((t (nil))))
     (header-line ((t (nil))))
     (help-argument-name ((t (nil))))
     (hi-black-b ((t (nil))))
     (hi-black-hb ((t (nil))))
     (hi-blue ((t (nil))))
     (hi-blue-b ((t (nil))))
     (hi-green ((t (nil))))
     (hi-green-b ((t (nil))))
     (hi-pink ((t (nil))))
     (hi-red-b ((t (nil))))
     (hi-yellow ((t (nil))))
     (highlight ((t (:background "darkseagreen2"))))
     (highlight-changes-delete-face ((t (nil))))
     (highlight-changes-face ((t (nil))))
     (highline-face ((t (:background "grey12"))))
     (highline-vertical-face ((t (:background "lightcyan"))))
     (holiday ((t (:background "orangered" :foreground "lightyellow"))))
     (hproperty:but-face ((t (:bold t :background "wheat" :foreground "medium violet red" :weight bold))))
     (hproperty:flash-face ((t (:bold t :background "wheat" :foreground "gray80" :weight bold))))
     (hproperty:highlight-face ((t (:bold t :background "wheat" :foreground "red" :weight bold))))
     (hproperty:item-face ((t (:bold t :weight bold))))
     (html-helper-bold-face ((t (nil))))
     (html-helper-bold-italic-face ((t (nil))))
     (html-helper-builtin-face ((t (nil))))
     (html-helper-italic-face ((t (nil))))
     (html-helper-underline-face ((t (nil))))
     (html-tag-face ((t (nil))))
     (hyper-apropos-documentation ((t (nil))))
     (hyper-apropos-heading ((t (nil))))
     (hyper-apropos-hyperlink ((t (nil))))
     (hyper-apropos-major-heading ((t (nil))))
     (hyper-apropos-section-heading ((t (nil))))
     (hyper-apropos-warning ((t (nil))))
     (ibuffer-deletion-face ((t (nil))))
     (ibuffer-marked-face ((t (nil))))
     (idlwave-help-link-face ((t (nil))))
     (idlwave-shell-bp-face ((t (nil))))
     (ido-first-match-face ((t (:bold t :weight bold))))
     (ido-indicator-face ((t (nil))))
     (ido-only-match-face ((t (:foreground "ForestGreen"))))
     (ido-subdir-face ((t (:foreground "red"))))
     (info-header-node ((t (nil))))
     (info-header-xref ((t (nil))))
     (info-menu-5 ((t (nil))))
     (info-menu-6 ((t (nil))))
     (info-menu-header ((t (nil))))
     (info-node ((t (:bold t :weight bold))))
     (info-xref ((t (:bold t :weight bold))))
     (isearch ((t (:background "paleturquoise"))))
     (isearch-secondary ((t (nil))))
     (iswitchb-current-match ((t (:foreground "firebrick"))))
     (iswitchb-invalid-regexp ((t (:bold t :weight bold :foreground "Red"))))
     (iswitchb-single-match ((t (:foreground "blue"))))
     (iswitchb-virtual-matches ((t (:foreground "red3"))))
     (italic ((t (:italic t :slant italic))))
     (jabber-activity-face ((t (:bold t :foreground "red" :weight bold))))
     (jabber-chat-error ((t (:bold t :foreground "red" :weight bold))))
     (jabber-chat-prompt-foreign ((t (:bold t :foreground "red" :weight bold))))
     (jabber-chat-prompt-local ((t (:bold t :foreground "blue" :weight bold))))
     (jabber-chat-prompt-system ((t (:bold t :foreground "green" :weight bold))))
     (jabber-chat-text-foreign ((t (nil))))
     (jabber-chat-text-local ((t (nil))))
     (jabber-rare-time-face ((t (:foreground "darkgreen" :underline t))))
     (jabber-roster-user-away ((t (:italic t :foreground "dark green" :slant italic :weight normal))))
     (jabber-roster-user-chatty ((t (:bold t :foreground "dark orange" :slant normal :weight bold))))
     (jabber-roster-user-dnd ((t (:italic t :foreground "red" :slant italic :weight normal))))
     (jabber-roster-user-error ((t (:italic t :foreground "red" :slant italic :weight light))))
     (jabber-roster-user-offline ((t (:italic t :foreground "dark grey" :slant italic :weight light))))
     (jabber-roster-user-online ((t (:bold t :foreground "blue" :slant normal :weight bold))))
     (jabber-roster-user-xa ((t (:italic t :foreground "black" :slant italic :weight normal))))
     (jabber-title-large ((t (:bold t :weight bold :height 3.0 :width ultra-expanded))))
     (jabber-title-medium ((t (:bold t :weight bold :height 2.0 :width expanded))))
     (jabber-title-small ((t (:bold t :weight bold :height 1.0 :width semi-expanded))))
     (jde-bug-breakpoint-cursor ((t (nil))))
     (jde-bug-breakpoint-marker ((t (nil))))
     (jde-db-active-breakpoint-face ((t (nil))))
     (jde-db-requested-breakpoint-face ((t (nil))))
     (jde-db-spec-breakpoint-face ((t (nil))))
     (jde-java-font-lock-api-face ((t (nil))))
     (jde-java-font-lock-bold-face ((t (nil))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (nil))))
     (jde-java-font-lock-doc-tag-face ((t (nil))))
     (jde-java-font-lock-italic-face ((t (nil))))
     (jde-java-font-lock-link-face ((t (nil))))
     (jde-java-font-lock-modifier-face ((t (nil))))
     (jde-java-font-lock-number-face ((t (nil))))
     (jde-java-font-lock-operator-face ((t (nil))))
     (jde-java-font-lock-package-face ((t (nil))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-underline-face ((t (nil))))
     (lazy-highlight ((t (nil))))
     (lazy-highlight-face ((t (nil))))
     (left-margin ((t (nil))))
     (linemenu-face ((t (nil))))
     (link ((t (:foreground "blue1" :underline t))))
     (link-visited ((t (:underline t :foreground "magenta4"))))
     (list-mode-item-selected ((t (:background "gray68" :foreground "black"))))
     (log-view-file-face ((t (nil))))
     (log-view-message-face ((t (nil))))
     (magenta ((t (nil))))
     (makefile-space-face ((t (nil))))
     (man-bold ((t (nil))))
     (man-heading ((t (nil))))
     (man-italic ((t (nil))))
     (man-xref ((t (nil))))
     (match ((t (:background "yellow"))))
     (menu ((t (nil))))
     (message-cited-text ((t (nil))))
     (message-cited-text-face ((t (:foreground "red"))))
     (message-header-cc-face ((t (:foreground "MidnightBlue"))))
     (message-header-contents ((t (nil))))
     (message-header-name-face ((t (:foreground "cornflower blue"))))
     (message-header-newsgroups-face ((t (:bold t :foreground "blue4" :weight bold))))
     (message-header-other-face ((t (:foreground "steel blue"))))
     (message-header-subject-face ((t (:bold t :foreground "navy blue" :weight bold))))
     (message-header-to-face ((t (:bold t :foreground "MidnightBlue" :weight bold))))
     (message-header-xheader-face ((t (:foreground "blue"))))
     (message-headers ((t (nil))))
     (message-highlighted-header-contents ((t (nil))))
     (message-mml-face ((t (:foreground "ForestGreen"))))
     (message-separator-face ((t (:foreground "brown"))))
     (message-url ((t (nil))))
     (minibuffer-prompt ((t (nil))))
     (mmm-default-submode-face ((t (:background "#c0c0c5"))))
     (mmm-face ((t (nil))))
     (mode-line ((t (nil))))
     (mode-line-buffer-id ((t (:background "Gray80" :foreground "blue4"))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (nil))))
     (modeline-mousable ((t (:background "Gray80" :foreground "firebrick"))))
     (modeline-mousable-minor-mode ((t (:background "Gray80" :foreground "green4"))))
     (mouse ((t (:background "black"))))
     (mpg123-face-cur ((t (nil))))
     (mpg123-face-slider ((t (nil))))
     (my-summary-highlight-face ((t (:background "PaleTurquoise4" :foreground "White"))))
     (my-tab-face ((t (nil))))
     (my-url-face ((t (:foreground "LightBlue"))))
     (next-error ((t (:foreground "light cyan" :background "sienna"))))
     (nil ((t (nil))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (overlay-empty-face ((t (nil))))
     (p4-diff-del-face ((t (nil))))
     (paren-blink-off ((t (:foreground "azure1"))))
     (paren-face ((t (:background "lightgoldenrod"))))
     (paren-face-match ((t (:background "turquoise"))))
     (paren-face-mismatch ((t (:background "purple" :foreground "white"))))
     (paren-face-no-match ((t (:background "yellow" :foreground "black"))))
     (paren-match ((t (:background "bisque2"))))
     (paren-mismatch ((t (:background "DeepPink" :foreground "black"))))
     (paren-mismatch-face ((t (:background "DeepPink"))))
     (paren-no-match-face ((t (:background "yellow"))))
     (pointer ((t (nil))))
     (primary-selection ((t (:background "gray65"))))
     (query-replace ((t (:background "paleturquoise"))))
     (reb-match-0 ((t (nil))))
     (reb-match-1 ((t (nil))))
     (reb-match-2 ((t (nil))))
     (reb-match-3 ((t (nil))))
     (red ((t (:foreground "red"))))
     (region ((t (:background "sienna" :foreground "light cyan"))))
     (right-margin ((t (nil))))
     (rpm-spec-dir-face ((t (nil))))
     (rpm-spec-doc-face ((t (nil))))
     (rpm-spec-ghost-face ((t (nil))))
     (rpm-spec-macro-face ((t (nil))))
     (rpm-spec-package-face ((t (nil))))
     (rpm-spec-tag-face ((t (nil))))
     (rpm-spec-var-face ((t (nil))))
     (ruler-mode-column-number-face ((t (:stipple nil :background "grey76" :foreground "black" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "outline-andale mono"))))
     (ruler-mode-current-column-face ((t (:bold t :stipple nil :background "grey76" :foreground "yellow" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight bold :width normal :family "outline-andale mono"))))
     (ruler-mode-default-face ((t (:stipple nil :background "grey76" :foreground "grey64" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "outline-andale mono"))))
     (ruler-mode-fill-column-face ((t (:stipple nil :background "grey76" :foreground "red" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "outline-andale mono"))))
     (ruler-mode-margins-face ((t (:stipple nil :background "grey64" :foreground "grey64" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "outline-andale mono"))))
     (ruler-mode-tab-stop-face ((t (:stipple nil :background "grey76" :foreground "steelblue" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "outline-andale mono"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "paleturquoise"))))
     (semantic-dirty-token-face ((t (nil))))
     (semantic-highlight-edits-face ((t (:background "gray90"))))
     (semantic-intangible-face ((t (nil))))
     (semantic-read-only-face ((t (nil))))
     (semantic-unmatched-syntax-face ((t (nil))))
     (senator-intangible-face ((t (nil))))
     (senator-momentary-highlight-face ((t (nil))))
     (senator-read-only-face ((t (nil))))
     (setnu-line-number-face ((t (:bold t :background "Grey15" :foreground "White" :weight bold))))
     (sgml-comment-face ((t (nil))))
     (sgml-doctype-face ((t (nil))))
     (sgml-end-tag-face ((t (nil))))
     (sgml-entity-face ((t (nil))))
     (sgml-ignored-face ((t (nil))))
     (sgml-ms-end-face ((t (nil))))
     (sgml-ms-start-face ((t (nil))))
     (sgml-pi-face ((t (nil))))
     (sgml-sgml-face ((t (nil))))
     (sgml-short-ref-face ((t (nil))))
     (sgml-shortref-face ((t (nil))))
     (sgml-start-tag-face ((t (nil))))
     (sh-heredoc-face ((t (nil))))
     (shadow ((t (:foreground "grey50"))))
     (shell-input-face ((t (:bold t :background "wheat" :foreground "blue" :weight bold))))
     (shell-option-face ((t (:foreground "gray50"))))
     (shell-output-2-face ((t (:foreground "green4"))))
     (shell-output-3-face ((t (:foreground "green4"))))
     (shell-output-face ((t (:bold t :weight bold))))
     (shell-prompt-face ((t (:foreground "blue3"))))
     (show-block-face1 ((t (nil))))
     (show-block-face2 ((t (nil))))
     (show-block-face3 ((t (nil))))
     (show-block-face4 ((t (nil))))
     (show-block-face5 ((t (nil))))
     (show-block-face6 ((t (nil))))
     (show-block-face7 ((t (nil))))
     (show-block-face8 ((t (nil))))
     (show-block-face9 ((t (nil))))
     (show-paren-match ((t (:background "grey30"))))
     (show-paren-mismatch ((t (:underline t))))
     (show-tabs-space-face ((t (nil))))
     (show-tabs-tab-face ((t (nil))))
     (smerge-base-face ((t (nil))))
     (smerge-markers-face ((t (nil))))
     (smerge-mine-face ((t (nil))))
     (smerge-other-face ((t (nil))))
     (special-string-face ((t (:foreground "light green"))))
     (speedbar-button-face ((t (:foreground "green4"))))
     (speedbar-directory-face ((t (:foreground "blue4"))))
     (speedbar-file-face ((t (:foreground "cyan4"))))
     (speedbar-highlight-face ((t (:background "green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (nil))))
     (speedbar-tag-face ((t (:foreground "brown"))))
     (strokes-char-face ((t (nil))))
     (swbuff-current-buffer-face ((t (nil))))
     (tabbar-button-face ((t (nil))))
     (tabbar-default-face ((t (nil))))
     (tabbar-selected-face ((t (nil))))
     (tabbar-separator-face ((t (nil))))
     (tabbar-unselected-face ((t (nil))))
     (template-message-face ((t (nil))))
     (term-black ((t (nil))))
     (term-blackbg ((t (nil))))
     (term-blue ((t (nil))))
     (term-blue-bold-face ((t (nil))))
     (term-blue-face ((t (nil))))
     (term-blue-inv-face ((t (nil))))
     (term-blue-ul-face ((t (nil))))
     (term-bluebg ((t (nil))))
     (term-bold ((t (nil))))
     (term-cyan ((t (nil))))
     (term-cyan-bold-face ((t (nil))))
     (term-cyan-face ((t (nil))))
     (term-cyan-inv-face ((t (nil))))
     (term-cyan-ul-face ((t (nil))))
     (term-cyanbg ((t (nil))))
     (term-default ((t (nil))))
     (term-default-bg ((t (nil))))
     (term-default-bg-inv ((t (nil))))
     (term-default-bold-face ((t (nil))))
     (term-default-face ((t (nil))))
     (term-default-fg ((t (nil))))
     (term-default-fg-inv ((t (nil))))
     (term-default-inv-face ((t (nil))))
     (term-default-ul-face ((t (nil))))
     (term-green ((t (nil))))
     (term-green-bold-face ((t (nil))))
     (term-green-face ((t (nil))))
     (term-green-inv-face ((t (nil))))
     (term-green-ul-face ((t (nil))))
     (term-greenbg ((t (nil))))
     (term-invisible ((t (nil))))
     (term-invisible-inv ((t (nil))))
     (term-magenta ((t (nil))))
     (term-magenta-bold-face ((t (nil))))
     (term-magenta-face ((t (nil))))
     (term-magenta-inv-face ((t (nil))))
     (term-magenta-ul-face ((t (nil))))
     (term-magentabg ((t (nil))))
     (term-red ((t (nil))))
     (term-red-bold-face ((t (nil))))
     (term-red-face ((t (nil))))
     (term-red-inv-face ((t (nil))))
     (term-red-ul-face ((t (nil))))
     (term-redbg ((t (nil))))
     (term-underline ((t (nil))))
     (term-white ((t (nil))))
     (term-white-bold-face ((t (nil))))
     (term-white-face ((t (nil))))
     (term-white-inv-face ((t (nil))))
     (term-white-ul-face ((t (nil))))
     (term-whitebg ((t (nil))))
     (term-yellow ((t (nil))))
     (term-yellow-bold-face ((t (nil))))
     (term-yellow-face ((t (nil))))
     (term-yellow-inv-face ((t (nil))))
     (term-yellow-ul-face ((t (nil))))
     (term-yellowbg ((t (nil))))
     (tex-math-face ((t (nil))))
     (texinfo-heading-face ((t (nil))))
     (text-cursor ((t (:background "Red3" :foreground "gray80"))))
     (tool-bar ((t (nil))))
     (tooltip ((t (nil))))
     (trailing-whitespace ((t (nil))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (nil))))
     (vc-annotate-face-0046FF ((t (nil))))
     (vcursor ((t (nil))))
     (vertical-border ((t (nil))))
     (vertical-divider ((t (nil))))
     (vhdl-font-lock-attribute-face ((t (:foreground "Orchid"))))
     (vhdl-font-lock-directive-face ((t (:foreground "CadetBlue"))))
     (vhdl-font-lock-enumvalue-face ((t (:foreground "SaddleBrown"))))
     (vhdl-font-lock-function-face ((t (:foreground "DarkCyan"))))
     (vhdl-font-lock-generic-/constant-face ((t (:foreground "Gold3"))))
     (vhdl-font-lock-prompt-face ((t (:bold t :foreground "Red" :weight bold))))
     (vhdl-font-lock-reserved-words-face ((t (:bold t :foreground "Orange" :weight bold))))
     (vhdl-font-lock-translate-off-face ((t (:background "LightGray"))))
     (vhdl-font-lock-type-face ((t (:foreground "ForestGreen"))))
     (vhdl-font-lock-variable-face ((t (:foreground "Grey50"))))
     (vhdl-speedbar-architecture-face ((t (:foreground "Blue"))))
     (vhdl-speedbar-architecture-selected-face ((t (:foreground "Blue" :underline t))))
     (vhdl-speedbar-configuration-face ((t (:foreground "DarkGoldenrod"))))
     (vhdl-speedbar-configuration-selected-face ((t (:foreground "DarkGoldenrod" :underline t))))
     (vhdl-speedbar-entity-face ((t (:foreground "ForestGreen"))))
     (vhdl-speedbar-entity-selected-face ((t (:foreground "ForestGreen" :underline t))))
     (vhdl-speedbar-instantiation-face ((t (:foreground "Brown"))))
     (vhdl-speedbar-instantiation-selected-face ((t (:foreground "Brown" :underline t))))
     (vhdl-speedbar-package-face ((t (:foreground "Grey50"))))
     (vhdl-speedbar-package-selected-face ((t (:foreground "Grey50" :underline t))))
     (vhdl-speedbar-subprogram-face ((t (:foreground "Orchid4"))))
     (viper-minibuffer-emacs-face ((t (:background "gray80" :foreground "black"))))
     (viper-minibuffer-insert-face ((t (:background "gray80" :foreground "black"))))
     (viper-minibuffer-vi-face ((t (:background "gray80" :foreground "black"))))
     (viper-replace-overlay-face ((t (:background "black" :foreground "white"))))
     (viper-search-face ((t (:background "black" :foreground "white"))))
     (vm-header-content-face ((t (:italic t :foreground "wheat" :slant italic))))
     (vm-header-from-face ((t (:italic t :foreground "wheat" :slant italic))))
     (vm-header-name-face ((t (:foreground "cyan"))))
     (vm-header-subject-face ((t (:foreground "cyan"))))
     (vm-header-to-face ((t (:italic t :foreground "cyan" :slant italic))))
     (vm-message-cited-face ((t (:foreground "Gray80"))))
     (vm-monochrome-image ((t (:background "white" :foreground "gray30"))))
     (vm-summary-face-1 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-2 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-3 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-4 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-highlight-face ((t (:foreground "White"))))
     (vm-xface ((t (nil))))
     (vmpc-pre-sig-face ((t (nil))))
     (vmpc-sig-face ((t (nil))))
     (vvb-face ((t (:background "pink" :foreground "gray30"))))
     (w3m-anchor-face ((t (nil))))
     (w3m-arrived-anchor-face ((t (nil))))
     (w3m-header-line-location-content-face ((t (nil))))
     (w3m-header-line-location-title-face ((t (nil))))
     (which-func ((t (:foreground "firebrick"))))
     (white ((t (nil))))
     (whitespace-highlight ((t (:background "green1"))))
     (widget ((t (nil))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "dark green"))))
     (widget-field ((t (:background "gray85"))))
     (widget-inactive ((t (:foreground "dim gray"))))
     (widget-single-line-field ((t (:background "royalblue"))))
     (woman-addition-face ((t (nil))))
     (woman-bold-face ((t (nil))))
     (woman-italic-face ((t (nil))))
     (woman-unknown-face ((t (nil))))
     (x-face ((t (nil))))
     (xrdb-option-name-face ((t (nil))))
     (xrdb-option-value-face ((t (:bold t :foreground "magenta" :weight bold))))
     (xref-error-face ((t (:foreground "red"))))
     (xref-keyword-face ((t (nil))))
     (xref-list-default-face ((t (nil))))
     (xref-list-pilot-face ((t (nil))))
     (xref-list-symbol-face ((t (nil))))
     (xsl-fo-alternate-face ((t (:foreground "Yellow"))))
     (xsl-fo-main-face ((t (:foreground "PaleGreen"))))
     (xsl-other-element-face ((t (:foreground "Coral"))))
     (xsl-xslt-alternate-face ((t (:foreground "LightGray"))))
     (xsl-xslt-main-face ((t (:foreground "Wheat"))))
     (xxml-emph-1-face ((t (:background "lightyellow"))))
     (xxml-emph-2-face ((t (:background "lightyellow"))))
     (xxml-header-1-face ((t (:background "seashell1" :foreground "MediumAquamarine"))))
     (xxml-header-2-face ((t (:background "seashell1" :foreground "SkyBlue"))))
     (xxml-header-3-face ((t (:background "seashell1"))))
     (xxml-header-4-face ((t (:background "seashell1"))))
     (xxml-interaction-face ((t (:background "lightcyan"))))
     (xxml-rug-face ((t (:background "cyan"))))
     (xxml-sparkle-face ((t (:background "yellow"))))
     (xxml-unbreakable-space-face ((t (:foreground "grey" :underline t))))
     (yellow ((t (:foreground "yellow"))))
     (zmacs-region ((t (:background "black" :foreground "white")))))))
(add-to-list 'color-themes '(my-color-theme  "My best" "Yury Luneff"))